#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFservice
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CustomerDB")]
	public partial class CustomerDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCustomer(Customer instance);
    partial void UpdateCustomer(Customer instance);
    partial void DeleteCustomer(Customer instance);
    #endregion
		
		public CustomerDBDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["constr"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public CustomerDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CustomerDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CustomerDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CustomerDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Customer> Customers
		{
			get
			{
				return this.GetTable<Customer>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Customers")]
	public partial class Customer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Customer_id;
		
		private string _Customer_name;
		
		private string _Customer_country;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCustomer_idChanging(int value);
    partial void OnCustomer_idChanged();
    partial void OnCustomer_nameChanging(string value);
    partial void OnCustomer_nameChanged();
    partial void OnCustomer_countryChanging(string value);
    partial void OnCustomer_countryChanged();
    #endregion
		
		public Customer()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Customer_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Customer_id
		{
			get
			{
				return this._Customer_id;
			}
			set
			{
				if ((this._Customer_id != value))
				{
					this.OnCustomer_idChanging(value);
					this.SendPropertyChanging();
					this._Customer_id = value;
					this.SendPropertyChanged("Customer_id");
					this.OnCustomer_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Customer_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Customer_name
		{
			get
			{
				return this._Customer_name;
			}
			set
			{
				if ((this._Customer_name != value))
				{
					this.OnCustomer_nameChanging(value);
					this.SendPropertyChanging();
					this._Customer_name = value;
					this.SendPropertyChanged("Customer_name");
					this.OnCustomer_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Customer_country", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Customer_mobile
		{
			get
			{
				return this._Customer_country;
			}
			set
			{
				if ((this._Customer_country != value))
				{
					this.OnCustomer_countryChanging(value);
					this.SendPropertyChanging();
					this._Customer_country = value;
					this.SendPropertyChanged("Customer_country");
					this.OnCustomer_countryChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
